backend:
  name: github
  repo: banser0125/B-R-Aby-cattery-site
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "site"
    label: "Website Content"
    files:
      - file: "content.json"
        label: "Homepage"
        name: "homepage"
        fields:
          - label: "Kings & Queens"
            name: "cats"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }

          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field:
              { label: "Image", name: "image", widget: "image" }
